### ISSUE TITLE
Traceback (most recent call last):   File "object_tracker.py", line 69, in <module>     detections = net.forward() cv2.error: OpenCV(4.0.0) /io/opencv/modules/dnn/src/layers/convolution_layer.cpp:236: error: (-215:Assertion failed) blobs.size() != 0 in function 'getMemoryShapes'

### ISSUE THREAD

**Issue by Sukhoimaster** [habom2310/People-tracking-with-Age-and-Gender-detection#3]
this is the following output :
  File "object_tracker.py", line 69, in <module>
    detections = net.forward()

cv2.error: OpenCV(4.0.0) /io/opencv/modules/dnn/src/layers/convolution_layer.cpp:236: error: (-215:Assertion failed) blobs.size() != 0 in function 'getMemoryShapes'

how can i resolve this.

**Comment by igaitan1991** [comment]
Hi Sukhoimaster,

Try to uncomment line 58 at object_tracker.py `frame = imutils.resize(frame, width=400)`.

BR.
